### ISSUE TITLE
WeaponTemplate json Issue From Trello

### ISSUE THREAD

**Issue by neilwhitlow** [richardhannah/MechForge#2]
Appears that HBS WeaponTemplate.json has an error, they missed a comma after the DisallowedLocations property, between it and the CriticalComponent property. So data, not code...Json.NET behaving properly

**Comment by neilwhitlow** [comment]
Likewise with CombatGameConstants... they forgot a comma between        
vfxPrfPrtl_artilleryImpact and cacheCount properties.

**Comment by richardhannah** [comment]
Cool good to know. I kinda toyed with the idea of creating something that would fix it... but for the sake of adding two commas to the data.... doesn't seem worth it. I think we can wait for HBS to fix their data on this one.
